# This workflow dpeloy the app to the server

name: Deploy client app

on:
  push:
    branches: [ pre-prod ]

jobs:
  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Remove previous back-up
      run: rm /home/prototype/wallofshame-frontend/build-backup/
    - name: Move previous build to back-up
      run: mv /home/prototype/wallofshame-frontend/build/ /home/prototype/wallofshame-frontend/build-backup/
    - name: Deploy to webroot
      run: mv build/ /home/prototype/wallofshame-frontend/build/